rm(list=ls())
setwd("~/Documents/project/whiplash-bpm/")

# install and load packages packages
packages = c("audio","Rcpp","ggplot2","signal", "MASS", "splines")
new.packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(packages, require, character.only=T)


source("fnc.R") # all the usefull R functions
sourceCpp("kalmanCpp.cpp")


signal <- load.wave("data/01-whiplash-begin.wav")[1,] # audio signal
N      <- length(signal)
fs     <- 48000 # sampling rate

# State Space
# we supposed that the the signal generated by a drum is an AR(1): s_t = a*s_{t-1} + b_t
# where a is the ar coefficient, and b_t ~ N(0, sigma^2_n) is a white noise 
# So the hypothesis test writes:
# H0 (absence of drum): x_t = b_t
# H1 (presence of drum) x_t = s_t b_t


# X(t) = F*X(t-1) + sigma_n*rho*v_t
# Y(t) = H*X(t) + sigma_n*w_t
# with w_t, v_t ~ N(0, 1)
# rho^2 = sigma_s^2/sigma_n^2, where sigma_s^2 is the variance of the innovation,
# and sigma_n^2 is the noise variance

Xt_t        <- 0 # initial state
F           <- -0.95 # ar coefficient
Q           <- 1
R           <- 1
H           <- 1
rho2        <- .5 # snr #.5
win.length  <- 2048  #2048 # length of the window used to estimate sigma^2_n #1024
slid.length <- 128  # overlap

# cusum (related to the likelihood ratio)
cusum <- kalmanCpp(Sig = signal, Q = Q,F = F, H = H, R = R, min_sigma2b = 1e-6,
                   rho2 = rho2, Qt_ = rep(0, N), winnoise = win.length, overlap=slid.length)[[1]]
cusum.log <- log(1+cusum)

X <- cbind(signal, cusum.log)
plot(as.ts(X[1:100000,]))

i = 1;
plot(as.ts(X[(100000*i):(100000*(i+1)),]))

peaks <- findPeaksCpp(X = cusum.log, threshold = 1, maxBPM = 1500, norm = TRUE,fs = fs)[[1]]

# Let compute the instantaneous bpm
# 1/(sec between detections)*60
bpm <- calc.bpm(peaks, fs)

(sum(peaks))

# PLOTSSSSS!

df  <- data.frame(x=1:length(bpm), y=bpm)
ggplot(data=df, aes(x=x,y=y))+geom_point(col = "#E41A1C",alpha=0.5)+
  stat_smooth(method=rlm,formula=y~ns(x,20),se=TRUE,level=0.99,span=0.2,n=2000,color="#377EB8", fill="#377EB8")+theme_mini(scale_text = 1.2, font = "Impact")+
  labs(title="Instantaneous BPM of Miles Teller\nin Whiplash (first scene)", x="beats", y="BPM")+
  ylim(0, 1200)
#ggsave("figs/bpm-whiplash-beginb.png", width=5, height=3)



## PLOT ILLUSTRATION

id1 <- 10e5-70000
id2 <- 10.5e5-70000
library(reshape2)

peaks.select <- peaks[id1:id2]
bpm1 <- round(calc.bpm(peaks.select,fs = fs))
id.nonnull <- which(peaks.select!=0)
x <- 1:length(id1:id2)
x.peaks <- x[id.nonnull]
bpm1 <- round(calc.bpm(peaks.select,fs = fs))
peaks.illu <- peaks.select[id.nonnull]

df.signal <- data.frame(x=x/fs, signal=as.numeric(signal[id1:id2]))
df.peaks <- data.frame(x=x.peaks/fs, peaks=peaks.illu*0.05, labs = c(paste0(bpm1), ""))
df.text  <- data.frame(x=(head(x.peaks, -1)+diff(x.peaks)/2)/fs, y=head(peaks.illu,-1)*0.05,labs=paste0(bpm1))

ggplot()+
  geom_point(data = df.peaks, aes(x=x,y=peaks, label=labs, col="#E41A1C"))+ggtitle("example with low BPM")+
  geom_text(data = df.text, aes(x=x,y=y, label=labs,family="Comfortaa"), size=7/2)+
  geom_line(data=df.signal, aes(x=x,y=signal))+theme_mini(scale_text = 1.2*3/2)+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank())+
  labs(title="example of beat detection for low BPM", x="time (s)", y="")+
  theme(plot.margin = unit(c(0.35, 0.2, 0.3, 0.35), "cm"), legend.position="none")

#ggsave("figs/testillua.png",width = 5*3/2, height = 5/2)




id1 <- 16e5
id2 <- 16.5e5
library(reshape2)

peaks.select <- peaks[id1:id2]
bpm1 <- round(calc.bpm(peaks.select,fs = fs))
id.nonnull <- which(peaks.select!=0)
x <- 1:length(id1:id2)
x.peaks <- x[id.nonnull]
bpm1 <- round(calc.bpm(peaks.select,fs = fs))
peaks.illu <- peaks.select[id.nonnull]

df.signal <- data.frame(x=x/fs, signal=as.numeric(signal[id1:id2]))
df.peaks <- data.frame(x=x.peaks/fs, peaks=peaks.illu*0.1, labs = c(paste0(bpm1), ""))
df.text  <- data.frame(x=(head(x.peaks, -1)+diff(x.peaks)/2)/fs, y=head(peaks.illu,-1)*0.1,labs=paste0(bpm1))

ggplot()+
  geom_point(data = df.peaks, aes(x=x,y=peaks, label=labs, col="#E41A1C"))+
  geom_text(data = df.text, aes(x=x,y=y, label=labs,family="Comfortaa"), size=7/2)+
  geom_line(data=df.signal, aes(x=x,y=signal))+theme_mini(scale_text = 1.2*3/2)+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank())+
  labs(title="example of beat detection for high BPM", x="time (s)", y="")+
  theme(plot.margin = unit(c(0.35, 0.2, 0.3, 0.35), "cm"), legend.position="none")+ylim(-0.09830012, 0.11)

ggsave("figs/testillub.png",width = 5*3/2, height = 5/2)
