rm(list=ls())
setwd("~/Documents/project/whiplash-bpm/")

# install and load packages packages
packages = c("audio","Rcpp","ggplot2","signal", "MASS", "splines")
new.packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(packages, require, character.only=T)


source("fnc.R") # all the usefull R functions
sourceCpp("kalmanCpp.cpp")


signal <- load.wave("data/03-fastest-drumer.wav")[1,] # audio signal
fs     <- 44100 # sampling rate

# High pass-filter because we want to detect abrupt change
# Also remove some noise
but     <- butter(4, 0.5, 'high')
s.filt  <- signal::filter(but,signal)[-(1:10)] # filter and remove 
N       <- length(s.filt)

# State Space
# we supposed that the the signal generated by a drum is an AR(1): s_t = a*s_{t-1} + b_t
# where a is the ar coefficient, and b_t ~ N(0, sigma^2_n) is a white noise 
# So the hypothesis test writes:
# H0 (absence of drum): x_t = b_t
# H1 (presence of drum) x_t = s_t b_t


# X(t) = F*X(t-1) + sigma_n*rho*v_t
# Y(t) = H*X(t) + sigma_n*w_t
# with w_t, v_t ~ N(0, 1)
# rho^2 = sigma_s^2/sigma_n^2, where sigma_s^2 is the variance of the innovation,
# and sigma_n^2 is the noise variance
Xt_t        <- 0 # initial state
F           <- -0.95 # ar coefficient
Q           <- 1
R           <- 1
H           <- 1
rho2        <- 100 # snr
win.length  <- 1024 # length of the window used to estimate sigma^2_n
slid.length <- 128  # overlap

# cusum (related to the likelihood ratio)
cusum <- kalmanCpp(Sig = s.filt, Q = Q,F = F, H = H, R = R, min_sigma2b =  .00001,
                 rho2 = rho2, Qt_ = rep(0, N), winnoise = win.length, overlap=slid.length)[[1]]
cusum.log <- log(1+cusum)


# We suppose that he can't drum quicker that 3000bpm
peaks <- findPeaksCpp(X = cusum.log, threshold = 2,
                      maxBPM = 3000, norm = TRUE,fs = fs)[[1]]
col <- peaks

# Let compute the instantaneous bpm
# 1/(sec between detections)*60
bpm <- calc.bpm(peaks, fs)

# 1211 instead of 1208 well... not so bad, few false detections
(sum(peaks))

# PLOTSSSSS!
col <- col[-which(col==0)]
df  <- data.frame(x=1:length(bpm), y=bpm, col = abs(diff(col)))
# ggplot(data=df, aes(x=x,y=y,col=col))+geom_point()+
#   geom_smooth()+theme_mini(scale_text = 1.2, font = "Impact")+
#   labs(title="Instantaneous BPM of The World's Fastest Drummer", x="beats", y="BPM")
# #ggsave("figs/bpm-wfd.png", width=6, height=3)


ggplot(data=df, aes(x=x,y=y))+geom_point(col = "#E41A1C",alpha=0.5)+
  geom_smooth(color="#377EB8", fill="#377EB8")+theme_mini(scale_text = 1.2, font = "Impact")+
  labs(title="Instantaneous BPM of The World's Fastest Drummer\n(during world record breaking)", x="beats", y="BPM")+ylim(0,2500)

#ggsave("figs/bpm-wfd.png", width=5, height=3)



data.regression <- data.frame(beats = 1:length(bpm), bpm = bpm)
attach(data.regression)
fit <- rlm(bpm ~ beats)
bpm.startend <- predict(fit, interval="confidence", level=.95)[c(10, 1200),]
