rm(list=ls())
setwd("~/Documents/project/whiplash-bpm/")

# install and load packages packages
packages = c("audio","Rcpp","ggplot2","signal", "MASS", "splines")
new.packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(packages, require, character.only=T)

# load all the usefull R+cpp functions
source("fnc.R") 
sourceCpp("kalmanCpp.cpp")


# Get the signal
signal <- load.wave("data/04-wfd-challenge.wav") # audio signal
signal <- (signal[1,] + signal[2,])/2
fs     <- 44100 # sampling rate

# Only the 40 first second are usefull
s.filt <- signal[1:(40*fs)]
N       <- length(s.filt)


# State Space
# we supposed that the the signal generated by a drum is an AR(1): s_t = a*s_{t-1} + b_t
# where a is the ar coefficient, and b_t ~ N(0, sigma^2_n) is a white noise 
# So the hypothesis test writes:
# H0 (absence of drum): x_t = b_t
# H1 (presence of drum) x_t = s_t + b_t


# X(t) = F*X(t-1) + sigma_n*rho*v_t
# Y(t) = H*X(t) + sigma_n*w_t
# with w_t, v_t ~ N(0, 1)
# rho^2 = sigma_s^2/sigma_n^2, where sigma_s^2 is the variance of the innovation,
# and sigma_n^2 is the noise variance
Xt_t        <- 0 # initial state
F           <- -0.95 # ar coefficient
Q           <- 1
R           <- 1
H           <- 1

rho2        <- .5   # snr
win.length  <- 2048 # length of the window used to estimate sigma^2_n
slid.length <- 128  # overlap

# cumulative sum (related to the likelihood ratio)
cusum <- kalmanCpp(Sig = s.filt, Q = Q,F = F, H = H, R = R, 
                   rho2 = rho2, Qt_ = rep(0, N), winnoise = win.length,
                   overlap=slid.length, min_sigma2b=.001)[[1]]

# The log is there to make it easy to choose a threshold
cusum.log <- log(1+cusum)


# We suppose that he can't drum quicker that 3000bpm
peaks <- findPeaksCpp(X = cusum.log, threshold = .4,
                      maxBPM = 3000, norm = TRUE,fs = fs)[[1]]

# Let compute the instantaneous bpm
# 1/(sec between detections)*60
bpm <- calc.bpm(peaks, fs)

(sum(peaks))

# PLOTS !
df  <- data.frame(x=1:length(bpm), y=bpm)
ggplot(data=df, aes(x=x,y=y))+geom_point(col = "#E41A1C",alpha=0.5)+
  geom_smooth(method=rlm,formula=y~ns(x,8),se=TRUE,level=0.99,color="#377EB8", fill="#377EB8")+
  theme_mini(scale_text = 1.2, font = "Impact")+
  labs(title="Instantaneous BPM of The World's Fastest Drummer\n(during challenge)", x="beats", y="BPM")+ylim(0,2000)

#ggsave("figs/bpm-wfdchallenge.png", width=5, height=3)